AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Dlt Motherduck Test Loader REST API
      StageName: v1
      Tags:
        stackName: !Ref AWS::StackName

  DltFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerTag: latest
      DockerBuildTarget: runner
    Properties:
      PackageType: Image
      FunctionName: dlt-motherduck-test-loader
      Timeout: 30 # default is 3 seconds, which is usually too little
      MemorySize: 512 # default is 128mb, which is too little
      Events:
        CollectApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /collect
            Method: POST
      Environment:
        Variables:
          DLT_PROJECT_DIR: "/tmp" # the only writeable directory on a lambda
          DLT_DATA_DIR: "/tmp" # the only writeable directory on a lambda
          DLT_PIPELINE_DIR: "/tmp" # the only writeable directory on a lambda
      Tags:
        stackName: !Ref AWS::StackName

  DltFunctionLogs:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DltFunction}"
      RetentionInDays: 30
      Tags:
        - Key: stackName
          Value: !Ref AWS::StackName

Outputs:
  ApiGateway:
    Description: !Sub "API Gateway endpoint URL for dlt-motherduck-test-loader Lambda function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/v1/collect/"
